# Generated by Django 5.2.11 on 2026-03-18 08:39

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('other', 'Other')], default='ko', max_length=32)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('model_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='files.fileai')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('file', 'File'), ('directory', 'Directory')], default='file', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('path', models.CharField(db_index=True, default='/', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('starred', models.BooleanField(default=False)),
                ('trashed', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=files.models.blob_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('other', 'Other')], default='en', max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blob', to='files.node')),
            ],
        ),
        migrations.AddField(
            model_name='fileai',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai', to='files.node'),
        ),
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_size', models.BigIntegerField(default=0)),
                ('used_size', models.BigIntegerField(default=0)),
                ('remaining_size', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['owner', 'parent'], name='files_node_owner_i_10f64d_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['owner', 'trashed'], name='files_node_owner_i_4a78be_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['owner', 'node_type'], name='files_node_owner_i_2dc3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['owner', '-created_at'], name='files_node_owner_i_df47d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('owner', 'parent', 'name'), name='uniq_node_name_per_parent'),
        ),
    ]
