# Generated by Django 5.2.13 on 2026-04-08 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileai',
            name='node',
        ),
        migrations.RemoveField(
            model_name='fileembedding',
            name='file_ai',
        ),
        migrations.RemoveConstraint(
            model_name='node',
            name='uniq_node_name_per_parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userstorage',
            name='remaining_size',
        ),
        migrations.AddField(
            model_name='fileblob',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='node',
            name='ext',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='path',
            field=models.CharField(db_index=True, default='/', max_length=1024),
        ),
        migrations.AddIndex(
            model_name='fileblob',
            index=models.Index(fields=['sha256'], name='files_fileb_sha256_2fe16f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileblob',
            index=models.Index(fields=['status'], name='files_fileb_status_b08e23_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['owner', 'path'], name='files_node_owner_i_b7b036_idx'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('owner', 'path'), name='uniq_node_path_per_owner'),
        ),
        migrations.DeleteModel(
            name='FileAI',
        ),
        migrations.DeleteModel(
            name='FileEmbedding',
        ),
    ]
