# Generated by Django 5.2.11 on 2026-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfile',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
