# Generated by Django 5.2.11 on 2026-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_userfile_starred_userfile_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
